[project]
name = "nova"
version = "0.1.0"
description = "Utility per PostgreSQL"
authors = [{ name = "Lorenzo Santarsieri" }]
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
